export const nodeFixes = {
    "fixes": {
        "gtUIInputNode": "Griptape Create: Text",
        "gtUICLIPTextEncode": "Griptape Create: CLIP Text Encode",
        "gtUITextToClipEncode": "Griptape Convert: Text to CLIP Encode",
        "gtUIFetchImage": "Griptape Load: Image From URL",
        "CreateAgent": "Griptape Create: Agent",
        "RunAgent": "Griptape Run: Agent",
        "PromptImageGenerationTask": "Griptape Create: Image from Text",
        "PromptImageVariationTask": "Griptape Create: Image Variation",
        "Rule": "Griptape Create: Rules",
        "RulesList": "Griptape Combine: Rules List",
        "gtUIOpenAiAudioTranscriptionDriver": "Griptape Driver: OpenAI",
        "gtUIAmazonBedrockStableDiffusionImageGenerationDriver": "Griptape Driver: Amazon Bedrock Stable Diffusion",
        "gtUIAmazonBedrockTitanImageGenerationDriver": "Griptape Driver: Amazon Bedrock Titan",
        "gtUILeonardoImageGenerationDriver": "Griptape Driver: Leonardo.AI",
        "gtUIOutputStringNode": "Griptape Display: Text",
        "gtUIOutputImageNode": "Griptape Display: Image",
        "gtUIOutputArtifactNode": "Griptape Display: Artifact",
        "ImageQueryTask": "Griptape Run: Image Description",
        "ParallelImageQueryTask": "Griptape Run: Parallel Image Description",
        "PromptTask": "Griptape Run: Prompt Task",
        "ToolTask": "Griptape Run: Tool Task",
        "ToolkitTask": "Griptape Run: Toolkit Task",
        "TextSummaryTask": "Griptape Run: Text Summary",
        "AudioTranscriptionTask": "Griptape Run: Audio Transcription",
        "ExpandAgent": "Griptape Expand: Agent Nodes",
        "gtUIOpenAiStructureConfig": "Griptape Agent Config: OpenAI",
        "gtUIAmazonBedrockStructureConfig": "Griptape Agent Config: Amazon Bedrock",
        "gtUIGoogleStructureConfig": "Griptape Agent Config: Google",
        "gtUIAnthropicStructureConfig": "Griptape Agent Config: Anthropic",
        "gtUIOllamaStructureConfig": "Griptape Agent Config: Ollama",
        "gtUILMStudioStructureConfig": "Griptape Agent Config: LM Studio",
        "Calculator": "Griptape Tool: Calculator",
        "DateTime": "Griptape Tool: DateTime",
        "WebScraper": "Griptape Tool: WebScraper",
        "gtUIFileManager": "Griptape Tool: FileManager",
        "gtAudioTranscriptionClient": "Griptape Tool: Audio Transcription",
        "gtUIKnowledgeBaseTool": "Griptape Tool: Griptape Cloud KnowledgeBase",
        "gtUIWebSearch": "Griptape Tool: WebSearch",
        "ToolList": "Griptape Combine: Tool List",
        "MergeTexts": "Griptape Combine: Merge Texts",
        "EnvironmentConfig": "Griptape Config: Environment Variables",
        "gtUIOpenAiImageGenerationDriver": "Griptape Audio Driver: OpenAI",
        "gtUILoadAudio": "Griptape Load: Audio",
        "Griptape Audio Driver: ElevenLabs": "Griptape Text To Speech Driver: ElevenLabs", 
        "Griptape Audio Driver: OpenAI": "Griptape Audio Transcription Driver: OpenAI"
    }
}