[tool.poetry]
name = "comfyui-griptape"
version = "0.1.0"
description = ""
authors = ["Jason Schleifer <jason.schleifer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
griptape = { version = "^0.33.0", extras = ["drivers-image-generation-huggingface","drivers-prompt-cohere","drivers-prompt-anthropic","drivers-prompt-huggingface-hub","drivers-prompt-amazon-bedrock","drivers-prompt-amazon-sagemaker","drivers-prompt-google","drivers-prompt-ollama","drivers-embedding-amazon-bedrock","drivers-embedding-amazon-sagemaker","drivers-embedding-huggingface","drivers-embedding-voyageai","drivers-embedding-google","drivers-embedding-cohere","drivers-embedding-ollama","drivers-vector-pinecone","drivers-vector-marqo","drivers-vector-mongodb","drivers-vector-redis","drivers-vector-opensearch","drivers-vector-pgvector","drivers-vector-postgresql","drivers-vector-qdrant","drivers-web-scraper-trafilatura","drivers-web-scraper-markdownify","drivers-web-search-duckduckgo","loaders-dataframe","loaders-pdf","loaders-image","loaders-email","loaders-audio", "drivers-text-to-speech-elevenlabs"]}
icecream = "^2.1.3"
torch = {version = "^2.3.1+cu121", source = "pytorch-gpu-src"}
torchvision = {version = "^0.18.1+cu121", source = "pytorch-gpu-src"}
torchaudio = {version = "^2.3.1+cu121", source = "pytorch-gpu-src"}
comfy-cli = "^1.1.5"

[tool.comfy]
PublisherId="shhlife"
DisplayName="Griptape"
Icon=""

[[tool.poetry.source]]
name = "pytorch-gpu-src"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
